# Generated by Django 5.2.7 on 2025-11-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_assignment_max_points_assignment_uploaded_by_quiz_and_more'),
        ('ta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taprofile',
            old_name='tasks',
            new_name='ta_tasks',
        ),
        migrations.AddField(
            model_name='taprofile',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='taprofile',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='taprofile',
            name='courses_assigned',
            field=models.ManyToManyField(blank=True, related_name='assigned_tas', to='core.course'),
        ),
        migrations.AlterField(
            model_name='taprofile',
            name='department',
            field=models.CharField(max_length=50),
        ),
    ]
