# Generated by Django 5.2.7 on 2025-11-19 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('faculty', '0002_facultyprofile_designation_facultyprofile_first_name_and_more'),
        ('students', '0001_initial'),
        ('ta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='max_points',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='assignment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_assignments', to='faculty.facultyprofile'),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField()),
                ('max_marks', models.FloatField(default=10.0)),
                ('duration_minutes', models.IntegerField(default=30)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='core.course')),
            ],
        ),
        migrations.CreateModel(
            name='TATask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('completion_notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='faculty.facultyprofile')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ta_tasks', to='core.course')),
                ('ta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='ta.taprofile')),
            ],
        ),
        migrations.CreateModel(
            name='QuizGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.FloatField(default=0.0)),
                ('remarks', models.TextField(blank=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='core.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_grades', to='students.studentprofile')),
            ],
            options={
                'unique_together': {('quiz', 'student')},
            },
        ),
    ]
