# Generated by Django 5.2.7 on 2025-11-20 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_assignment_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='faculty',
        ),
    ]
