# Generated by Django 5.2.7 on 2025-11-20 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_course_faculty'),
        ('faculty', '0002_facultyprofile_designation_facultyprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='faculty.facultyprofile'),
        ),
    ]
