# Generated by Django 5.2.8 on 2025-11-20 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_attendance_unique_together_and_more'),
        ('faculty', '0002_facultyprofile_designation_facultyprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to='faculty.facultyprofile'),
        ),
    ]
