# Generated by Django 5.2.7 on 2025-11-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_course_faculty'),
        ('faculty', '0002_facultyprofile_designation_facultyprofile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='faculty',
        ),
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.ManyToManyField(blank=True, related_name='courses', to='faculty.facultyprofile'),
        ),
    ]
